export enum LocalStorageKeys {
  CART_ITEMS = 'CART_ITEMS',
  CART_ITEMS_PLACE_ID = 'CART_ITEMS_PLACE_ID',
  USERS_LIST = 'USERS_LIST',
  USER_AUTHENTICATED = 'USER_AUTHENTICATED',
  USER_ADDRESSES = 'USER_ADDRESSES',
}
